### ISSUE TITLE
Issue with changing email preference by end user

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#69]
@cgladue I was in my account robg_xclub@peakmarketing.com and on the Manage Account section I saw the the box to receive email was unchecked.  So I checked it, and it seemed to hang, and then I received an email from mail chip to subscribe, which is fine.  So I went to my email, clicked on the link in the email to subscribe, it took me to the mailchip page that I created, again which is fine.

Then I clicked the link to "Continue to the website" and it took a real long time again... So I came here and started writing this...  When I went back to the original tab that I was logged into in my Magange Account section, I saw the screen/image directly below.

When I went back to the tab that spawned from the click in the email AFTER I clicked subscribe on the mailchip page, I saw the second image/screen below.

Seems like the "Please check your email to confirm your subscription preference." should show up on the screen right after clicking "Save" when I change my preferences.

The other thing is, now that I did change my preferences, when I look in my Manage account section, I don't see the check mark that would show I am subscribed... Third picture below...  

Please see if you can try it yourself and see what happens...

![uploads/3bdb64c2-bd29-4627-b15a-5f30d24ae499/Screen Shot 2018-03-23 at 2.13.41 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F3bdb64c2-bd29-4627-b15a-5f30d24ae499%2FScreen+Shot+2018-03-23+at+2.13.41+PM.png)

--

![uploads/73515d86-9704-4c42-a30c-848d708100c8/Screen Shot 2018-03-23 at 2.16.19 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F73515d86-9704-4c42-a30c-848d708100c8%2FScreen+Shot+2018-03-23+at+2.16.19+PM.png)

--

![uploads/39dc4217-a953-46ad-8091-2bd54461b347/Screen Shot 2018-03-23 at 2.20.47 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F39dc4217-a953-46ad-8091-2bd54461b347%2FScreen+Shot+2018-03-23+at+2.20.47+PM.png)

**Comment by cgladue** [comment]
identified a change int he mailchimp API that caused the value int he DB to not get set... fixed that but now even tho the field in the DB is true, the checkbox is not getting set ... reassigning to @ChrisASearles

**Comment by ChrisASearles** [comment]
Fixed and committed.

**Comment by cgladue** [comment]
@robgpeak Published

**Comment by robgpeak** [comment]
https://screencast.com/t/9cxh1fv3T4ua here is the screencast of what happens.  I can opt out in my manage account section, but when I try ti opt back in, it times out.

**Comment by robgpeak** [comment]
by the way, I DO get an email from mailchip asking me to click the link to subscribe to the list.  So even though it timed out on our end, seemingly MC is getting the request from us to change the opt-in/out status.

**Comment by robgpeak** [comment]
@ChrisASearles this is still happening.  I was in my x6@peakmarketing.com account in xclub.complinks.co and I clicked the check mark to receive email notifications, I received the email to subscribe to the list from mailchimp, but the xclub.complinks.co site timed out with the 524 error image posted earlier in this thread.

I'm not sure if this is relevant but I was looking in the list of X Club in MailChimp and I saw that this email address was already subscribed, even though the checkbox in the manage account section was NOT check. I thought I would tell you I don't know if it makes a difference.

**Comment by ChrisASearles** [comment]
@robgpeak I know we spoke about this yesterday and I hadn't read these comments prior to that conversation. There was an issue on our end that has been fixed and I was able to confirm that it is working properly. This function is hanging on the call into the MailChimp API so it's something @cgladue will have to look into.

**Comment by robgpeak** [comment]
@cgladue do you need a screencast of what's happening?

**Comment by cgladue** [comment]
no i think what you are saying is its timing out just like the forgot
password was...

if its mailchimp being slow i may be limited on what i can do but im
looking at it



Chad Gladue
*DevNull Technology, LLC*

**Comment by cgladue** [comment]
@robgpeak this should be all set now

**Comment by robgpeak** [comment]
Excellent!
